server:
  port: 8029

spring:
  application:
    name: gcl.kzl.feign.client

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://192.168.138.128:8761/eureka/
    healthcheck:
      enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  okhttp:
    enabled: true